# Generated by Django 5.2.6 on 2025-09-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
