# Generated by Django 5.2.6 on 2025-09-20 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='team',
            name='name_kk',
        ),
        migrations.RemoveField(
            model_name='team',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='team',
            name='role_en',
        ),
        migrations.RemoveField(
            model_name='team',
            name='role_kk',
        ),
        migrations.RemoveField(
            model_name='team',
            name='role_ru',
        ),
    ]
