# Generated by Django 5.2.6 on 2025-09-22 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_team_name_en_remove_team_name_kk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='image',
        ),
        migrations.CreateModel(
            name='CaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='case_images/')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.case')),
            ],
        ),
    ]
