# Generated by Django 5.2.6 on 2025-09-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_logo_options_news_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
