# Generated by Django 5.2.6 on 2025-09-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_team_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-created_at'], 'verbose_name': 'Кейс', 'verbose_name_plural': 'Кейсы'},
        ),
        migrations.AlterModelOptions(
            name='caseimage',
            options={'ordering': ['created_at'], 'verbose_name': 'Изображение кейса', 'verbose_name_plural': 'Изображения кейсов'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.RemoveField(
            model_name='case',
            name='description',
        ),
        migrations.RemoveField(
            model_name='case',
            name='description_kk',
        ),
        migrations.RemoveField(
            model_name='case',
            name='title',
        ),
        migrations.RemoveField(
            model_name='case',
            name='title_kk',
        ),
        migrations.RemoveField(
            model_name='logo',
            name='title',
        ),
        migrations.RemoveField(
            model_name='news',
            name='description',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title',
        ),
        migrations.RemoveField(
            model_name='team',
            name='description',
        ),
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='role',
        ),
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.AddField(
            model_name='case',
            name='translation_status',
            field=models.CharField(choices=[('auto', 'Автоматический'), ('manual', 'Ручной'), ('none', 'Не переведен')], default='none', max_length=10, verbose_name='Статус перевода'),
        ),
        migrations.AddField(
            model_name='logo',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название (английский)'),
        ),
        migrations.AddField(
            model_name='logo',
            name='title_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название (русский)'),
        ),
        migrations.AddField(
            model_name='logo',
            name='translation_status',
            field=models.CharField(choices=[('auto', 'Автоматический'), ('manual', 'Ручной'), ('none', 'Не переведен')], default='none', max_length=10, verbose_name='Статус перевода'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=models.TextField(blank=True, max_length=999, null=True, verbose_name='Описание (английский)'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=models.TextField(blank=True, max_length=999, null=True, verbose_name='Описание (русский)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (английский)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (русский)'),
        ),
        migrations.AddField(
            model_name='news',
            name='translation_status',
            field=models.CharField(choices=[('auto', 'Автоматический'), ('manual', 'Ручной'), ('none', 'Не переведен')], default='none', max_length=10, verbose_name='Статус перевода'),
        ),
        migrations.AddField(
            model_name='team',
            name='description_en',
            field=models.TextField(blank=True, max_length=350, null=True, verbose_name='Описание (английский)'),
        ),
        migrations.AddField(
            model_name='team',
            name='description_ru',
            field=models.TextField(blank=True, max_length=350, null=True, verbose_name='Описание (русский)'),
        ),
        migrations.AddField(
            model_name='team',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя (английский)'),
        ),
        migrations.AddField(
            model_name='team',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя (русский)'),
        ),
        migrations.AddField(
            model_name='team',
            name='role_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Роль (английский)'),
        ),
        migrations.AddField(
            model_name='team',
            name='role_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Роль (русский)'),
        ),
        migrations.AddField(
            model_name='team',
            name='translation_status',
            field=models.CharField(choices=[('auto', 'Автоматический'), ('manual', 'Ручной'), ('none', 'Не переведен')], default='none', max_length=10, verbose_name='Статус перевода'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок (английский)'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок (русский)'),
        ),
        migrations.AddField(
            model_name='video',
            name='translation_status',
            field=models.CharField(choices=[('auto', 'Автоматический'), ('manual', 'Ручной'), ('none', 'Не переведен')], default='none', max_length=10, verbose_name='Статус перевода'),
        ),
        migrations.AlterField(
            model_name='case',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='case',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (английский)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (русский)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок (английский)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок (русский)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='caseimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(upload_to='logo_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news_photos/', verbose_name='Изображение'),
        ),
    ]
